name: My first workflow
on: push
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "Hello, github Actions!"
      - name: Print message again
        run: echo "Tanish Setia"
  say-bye:
    needs: say-hello
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "bye from 2nd job"